version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3004:3004"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
